### ISSUE TITLE
How to use coil.callback?

### ISSUE THREAD

**Issue by flamendless** [rxi/coil#1]
hi, how does one use the `coil.callback` ? I already have this test
```lua
local coil = require("coil")

function love.load()
	coil.add(function()
  	    cb = coil.callback()
  	    coil.wait(cb)
  	    print("Hello world")
	end)
end

function love.update(dt)
	coil.update(dt)
end
```
i cant seem to make it print :/

**Comment by rxi** [comment]
If you use an object returned by `coil.callback` with `coil.wait`, the task will wait until that object is called. Adding the following to the end of your code snippet will continue the task and print `"Hello world"` when a key is pressed:

```lua
function love.keypressed()
  cb()
end
```

**Comment by flamendless** [comment]
Oh i see. But setting `cb` inside the coil function makes it unavailable outside. So i think that the code in the readme should be
```lua
cb = coil.callback()
coil.add(function()
    coil.wait(cb)
    print("Hello World")
end)

cb()
```

Thanks for the response! 

_Sent from my Liquid Zest 4G using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rxi** [comment]
In the example `cb` is a global. I think some of the confusion may have stemmed from the fact that the function passed to `coil.add()` is not ran until `coil.update()` is next called. I've updated `README.md` to make this behaviour clearer: 807e4967bfb961f0234afb7346dad011bfb86913
