### ISSUE TITLE
Coil Callback is called immediately

### ISSUE THREAD

**Issue by flamendless** [rxi/coil#2]
Hi, using this setup:
```
local cb = coil.callback()
coil.add(function()
  coil.wait(cb)
  print(1)
  coil.wait(cb)
  print(2)
end)

function love.keypressed(key)
  if key == "s" then cb() end
end
```
When I press "s" once, it prints 1 and 2.

Is this really the behaviour? Do i need to make many `var = coil.callback` to achieve what i want?

**Comment by rxi** [comment]
`coil.callback()` callbacks were designed to be passed to existing libraries that use a callback function to signal a one-off event, for example, a tweening library that calls an `onComplete` function when a tween has finished. They weren't designed to be used more than once. I believe adding support for several uses would be trivial: changing `task.wait.ready` back to `false` at line `76`.

Would you mind sharing what your use case is that requires this behaviour?

**Comment by flamendless** [comment]
Oh i see. I tried using coil to implement some sort of hacky sequence of events.

Like
Tween object to this (also using flux), on oncomplete, i just call a function
```
local function proceed()
  --other stuffs
  cb()
end
```

The sequence is like
```
cb = coil.callback()
coil.add(function()
  coil.wait(cb)
  --do event 1 (repeat the tween but with different parameters now)
  coil.wait(cb)
  -- repeat again but with diff parameter
  --and so on
end)
```

**Comment by rxi** [comment]
It is probably best to create a new callback object each time in the case you described, you could make the change I described above but without testing things I don't know if that would cause some other issues I hadn't considered.

The typical pattern I personally follow when using the library with flux would be something like this:
```lua
coil.add(function()
  local cb = coil.callback()
  flux.to(player, 1, { x = 0, y = 0 }):oncomplete(cb)
  coil.wait(cb)
  -- do other stuff

  local cb = coil.callback()
  flux.to(player, 1, { x = 10, y = 20 }):oncomplete(cb)
  coil.wait(cb)
  -- do other stuff
end)
```

In your case you can probably just do: `cb = coil.callback()` after each `coil.wait(cb)`

**Comment by flamendless** [comment]
Thanks!
